version: '3.8'
services:
  discord-bot:
    build: .
    image: my-discord-bot
    container_name: my-discord-bot-instance
    env_file: .env
    ports:
      - "3000:3000" # Si necesitas exponer algún puerto, descomenta esta línea y ajusta los números de puerto según sea necesario
